import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

const swSelf = self as any;

swSelf.skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

swSelf.addEventListener("message", (event: any) => {
  if (event.data && event.data.type === "SKIP_WAITING") swSelf.skipWaiting();
});

// Precache all assets generated by Vite
// Workbox will replace self.__WB_MANIFEST with the precache manifest array.
precacheAndRoute(self.__WB_MANIFEST || []);

// --- PWABuilder Required Logic Events ---

/**
 * 1. Fetch Event (Bulletproof Offline Support)
 * PWABuilder looks for a fetch listener that handles navigation requests.
 */
swSelf.addEventListener('fetch', (event: any) => {
  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request).catch(() => {
        return caches.match('/index.html') as Promise<Response>;
      })
    );
  }
});

/**
 * 2. Push Notifications
 * Full support for incoming background notifications.
 */
swSelf.addEventListener('push', (event: any) => {
  let data: any = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch (e) {
    data = { title: 'Blink', body: event.data ? event.data.text() : 'New message', senderId: 'unknown' };
  }
  
  const title = data.title || 'Blink';
  const senderId = data.senderId || 'unknown';
  const tag = `blink-msg-${senderId}`; // Batching by senderId
  
  const options = {
    body: data.body || 'New message in Blink',
    icon: '/icon-512.png',
    badge: '/icon-192.png',
    tag: tag,
    renotify: true,
    data: {
      url: data.url || '/',
    },
    actions: [
      { action: 'open', title: 'Open' },
      { action: 'close', title: 'Dismiss' }
    ]
  };

  event.waitUntil(swSelf.registration.showNotification(title, options));
});

/**
 * 3. Background Sync
 * Allows the app to retry sending messages even if the tab is closed.
 */
swSelf.addEventListener('sync', (event: any) => {
  console.log('[Service Worker] Background Sync:', event.tag);
  if (event.tag === 'sync-messages') {
    // Logic to retry failed message sends
  }
});

/**
 * 4. Periodic Background Sync
 * Used for updating content (like status updates) in the background.
 */
swSelf.addEventListener('periodicsync', (event: any) => {
  console.log('[Service Worker] Periodic Sync:', event.tag);
  if (event.tag === 'content-update') {
    // Logic to pre-fetch new chats/statuses
  }
});

// --- Standard Asset Routing ---

// Static Assets: StaleWhileRevalidate
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-assets',
  })
);

// Images: CacheFirst (with 30-day expiration)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60,
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Notification Click Handler
swSelf.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  const urlToOpen = event.notification.data.url || '/';

  event.waitUntil(
    swSelf.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients: any[]) => {
      for (let client of windowClients) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      if (swSelf.clients.openWindow) {
        return swSelf.clients.openWindow(urlToOpen);
      }
    })
  );
});
